# Source this file from an MSYS2 UCRT64 shell.
export WM_PROJECT=OpenFOAM WM_PROJECT_VERSION=dev
export WM_PROJECT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
export WM_PROJECT_INST_DIR=${WM_PROJECT_DIR%/*}
export WM_THIRD_PARTY_DIR=$WM_PROJECT_INST_DIR/ThirdParty-dev
export WM_PROJECT_USER_DIR=$WM_PROJECT_INST_DIR/user
export WM_ARCH=mingw64 WM_ARCH_OPTION=64 WM_COMPILER=Gcc
export WM_COMPILER_TYPE=system WM_OSTYPE=MSwindows WM_MPLIB=MSMPI FOAM_MPI=msmpi
export MPI_BUFFER_SIZE=${MPI_BUFFER_SIZE:-20000000}
export FOAM_BASH=$(cygpath -m /usr/bin/bash.exe)
export WM_PRECISION_OPTION=DP WM_LABEL_SIZE=32 WM_LABEL_OPTION=Int32
export WM_COMPILE_OPTION=${WM_COMPILE_OPTION:-Opt}
export WM_OPTIONS=$WM_ARCH$WM_COMPILER$WM_PRECISION_OPTION$WM_LABEL_OPTION$WM_COMPILE_OPTION
export WM_LINK_LANGUAGE=c++ WM_DIR=$WM_PROJECT_DIR/wmake
export FOAM_APPBIN=$WM_PROJECT_DIR/platforms/$WM_OPTIONS/bin
export FOAM_LIBBIN=$WM_PROJECT_DIR/platforms/$WM_OPTIONS/lib
export FOAM_EXT_LIBBIN=$WM_PROJECT_INST_DIR/ThirdParty-dev/platforms/lib
export FOAM_USER_APPBIN=$WM_PROJECT_USER_DIR/platforms/$WM_OPTIONS/bin
export FOAM_USER_LIBBIN=$WM_PROJECT_USER_DIR/platforms/$WM_OPTIONS/lib
export SCOTCH_TYPE=MSYS2 SCOTCH_ARCH_PATH=/ucrt64 SCOTCH_VERSION=system
export SCOTCH_INCLUDE_DIR=/ucrt64/include SCOTCH_LIB_DIR=/ucrt64/lib
export PTSCOTCH_INCLUDE_DIR=/ucrt64/include PTSCOTCH_LIB_DIR=/ucrt64/lib
export METIS_TYPE=MSYS2 METIS_ARCH_PATH=/ucrt64 METIS_VERSION=system
export PARMETIS_TYPE=MSYS2 PARMETIS_ARCH_PATH=/ucrt64 PARMETIS_VERSION=system
export ZOLTAN_TYPE=Windows ZOLTAN_VERSION=3.90
export ZOLTAN_ARCH_PATH=$WM_THIRD_PARTY_DIR/platforms/zoltan
export FOAM_SRC=$WM_PROJECT_DIR/src FOAM_ETC=$WM_PROJECT_DIR/etc
export FOAM_APP=$WM_PROJECT_DIR/applications FOAM_TUTORIALS=$WM_PROJECT_DIR/tutorials
export FOAM_SOLVERS=$FOAM_APP/solvers FOAM_UTILITIES=$FOAM_APP/utilities
export FOAM_MODULES=$FOAM_APP/modules
export FOAM_RUN=$WM_PROJECT_USER_DIR/run FOAM_JOB_DIR=$WM_PROJECT_INST_DIR/jobControl
export PATH=/ucrt64/bin:$WM_DIR:$WM_PROJECT_DIR/bin:$FOAM_APPBIN:$FOAM_LIBBIN:$PATH
export MSYS2_ARG_CONV_EXCL=
export MSYS=winsymlinks:lnk
